using InvoiceFlow.Domain.Entities;

namespace InvoiceFlow.Domain.Services;

/// <summary>
/// Handles creation and revocation of <see cref="RefreshToken"/>.
/// Token values are generated by the caller (Infrastructure JWT service)
/// and passed in as opaque strings.
/// </summary>
public sealed class RefreshTokenDomainService
{
    /// <summary>
    /// Creates a new refresh token for a user.
    /// <paramref name="token"/> must be a cryptographically random Base64Url string.
    /// </summary>
    public RefreshToken Create(Guid userId, string token, int expiryDays = 7)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(token);
        ArgumentOutOfRangeException.ThrowIfLessThan(expiryDays, 1);

        return new RefreshToken
        {
            UserId = userId,
            Token = token,
            ExpiresAt = DateTime.UtcNow.AddDays(expiryDays)
        };
    }

    /// <summary>
    /// Revokes a token, optionally recording the token that replaced it (rotation case).
    /// </summary>
    public void Revoke(RefreshToken refreshToken, string reason, string? replacedByToken = null)
    {
        ArgumentNullException.ThrowIfNull(refreshToken);
        ArgumentException.ThrowIfNullOrWhiteSpace(reason);

        refreshToken.IsRevoked = true;
        refreshToken.RevokedReason = reason;
        refreshToken.ReplacedByToken = replacedByToken;
    }
}
